[package]
name = "bwidman-twhite-avidf-project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gfx = "0.18.3"
gfx_device_gl = "0.16.2"
gl = "0.14.0"
piston_window = "0.128.0"
